
server:
  port: 8092

spring:
  application:
    name: YuanApi-Interface
  # datasource config
  datasource:
    url: jdbc:mysql://localhost:3306/yuan_api
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

# swagger config
swagger:
  title: YuanApi-Interface
  description: API documentation for Yuan Api Interface.
  version: 1.0.0

# base-packages
packages:
  controller: com.imyuanxiao.yuanapiinterface.controller
