server:
  port: 8080

spring:
  application:
    name: YuanApi
  # datasource config
  datasource:
    url: jdbc:mysql://localhost:3306/yuan_api
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


# swagger config
swagger:
  title: YuanApi-Admin
  description: API documentation for Yuan Api Admin.
  version: 1.0.0

# base-packages
packages:
  controller: com.imyuanxiao.yuanapiadmin.controller

# MyBatis-Plus
mybatis-plus:
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1

# dubbo 提供者
dubbo:
  application:
    name: dubbo-provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
